version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:8.13.4
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}
      - "9300:9300"
    volumes:
      - .es:/usr/share/elasticsearch/data
    networks:
      - default

  kibana:
    image: kibana:8.13.4
    hostname: kibana
    ports:
      - ${KIBANA_PORT}:${KIBANA_PORT}
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:${ELASTICSEARCH_PORT}
    depends_on:
      - elasticsearch
    networks:
      - default

networks:
  default:
